### ISSUE TITLE
Support passing results of outer component(s) to inner component(s)

### ISSUE THREAD

**Issue by erikthedeveloper** [jmeas/react-composer#28] opened 2018-02-08 14:32 UTC
As I was investigating whether `react-composer` supported passing the results of outer render prop components to inner render prop components, I saw that this topic recently came up in #7 as @jmeas described as:

> [...] a mode where each component gets passed the results of the past one. This allows for some very sophisticated composition of function components [...]

```jsx
// From https://github.com/jmeas/react-composer/issues/7#issuecomment-362946205
<Composer
  // Opt into props.components as functions
  functional
  components={[
    (resultThree, resultTwo) => <RenderPropComponent {...configOne} />,
    (resultThree) => <RenderPropComponent {...configTwo} />,
    () => <RenderPropComponent {...configThree} />
  ]}>
  {([resultOne, resultTwo, resultThree]) => (
    <MyComponent results={[resultOne, resultTwo, resultThree]} />
  )}
</Composer>
```

This is something I commonly need when manually composing render prop components so I'm excited to see it being discussed here 😃 .

Some thoughts I have around the idea:

### Keeping signature consistent

Where the primary `Composer.props.children` signature is 

```js
([resultOne, resultTwo]) => {/* ... */}
```

I feel like it would be more consistent to follow that for the `Composer.props.components` entries as functions also. 

So rather than 

```js
[
  (resultOne, resultTwo) => {/* ... */},
  (resultOne) => {/* ... */},
  () => {/* ... */},
]
```

It would be

```js
[
  ([resultOne, resultTwo]) => {/* ... */},
  ([resultOne]) => {/* ... */},
  ([]) => {/* ... */},
]
```

### Support both `element` and `function` without requiring opt-in flag

Part of me likes the explicit `props.functional` from @jmeas example, but part of me wonders if both `element` and `function` could both be supported via a type check so this is a first class API rather than an opt-in alternative API. 

Proposed API example usage (_assuming a shift to first:Outer last:Inner as being discussed in #7_)

```jsx
<Composer
  components={[
    <Outer {...outerProps} />,
    <Middle {...middleProps} />,
    ([outerResult, middleResult]) => <InnerNeedsResults {...outerResult} {...middleResult} />,
  ]}>
  {([outerResult, middleResult, innerResult]) => (
    <MyComponent results={[outerResult, middleResult, innerResult]} />
  )}
</Composer>
```

As for how to achieve this, I roughly played with this idea after looking at this section of `chainComponents`

https://github.com/jmeas/react-composer/blob/02d11f844e40e09633fd2f069e1d96cd8339d410/src/index.js#L43-L52

and came up with this (totally untested ⚠️ 😄)

```js
let component = components[componentIndex];

// ... 

if (typeof component === 'function') {
  // This entry from props.components is a function!
  // Invoke it with the currently accumulated results to produce the element.
  component = component([...results]);
}

// component is an element as it always was. Business as usual...
return React.cloneElement(component, {/* ... */});
```

---

:memo: As I was thinking about this and writing this, I realized just how confusing it can be with either RTL or LTR ordering. I might suggest using language such as "outer", "middle" , "inner" in the README and examples. That just feels more explicit/clear to me and eliminates a bit of mental parsing (especially for those not super familiar with composition in general and especially within React).

**Comment by jmeas** [comment] 2018-02-08 15:17
Thanks for the issue! I’m going to close this as a duplicate of #19, but you should _definitely_ copypasta this over there! Tons of good stuff here :v:

thanks again :)

**Closed by jmeas** 2018-02-08 15:17 UTC
Labels: duplicate
